# Slack configurations
SLACK_API_TOKEN = 'YOUR_SLACK_API_TOKEN'

# MySQL configurations
MYSQL_HOST = 'YOUR_MYSQL_HOST'
MYSQL_USER = 'YOUR_MYSQL_USER'
MYSQL_PASSWORD = 'YOUR_MYSQL_PASSWORD'
MYSQL_DB = 'YOUR_MYSQL_DB'

# Telegram configurations
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
CHAT_ID = -YOUR_CHAT_ID

MYSQL_CONNECTION_CONFIG = {
    'user': MYSQL_USER,
    'password': MYSQL_PASSWORD,
    'host': MYSQL_HOST,
    'database': MYSQL_DB,
}